name: CI
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install ragel
        run: sudo apt install ragel
      - name: Run tests
        run: |
          cd tests
          make test-travis
  build-simulator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install ragel
        run: sudo apt install ragel
      - name: Build simulator
        run: |
          cd simulator
          make
  build-firmware:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install ragel
        run: sudo apt install ragel
      - name: Prepare AVR32 toolchain
        run: |
          mkdir -p toolchain
          cd toolchain
          git clone https://github.com/monome/avr32-toolchain-linux.git deps/avr32-toolchain-linux
          cd deps/avr32-toolchain-linux
          tar xvfz avr32-gnu-toolchain-3.4.3.820-linux.any.x86_64.tar.gz
          mv avr32-gnu-toolchain-linux_x86_64 $GITHUB_WORKSPACE/avr32-tools
          chmod u+x $GITHUB_WORKSPACE/avr32-tools/bin/*
          echo $GITHUB_WORKSPACE/avr32-tools/bin >> $GITHUB_PATH
          unzip avr32-headers-6.2.0.742.zip -d $GITHUB_WORKSPACE/avr32-tools/avr32/include
      - name: Build module firmware
        run: |
          cd module
          make
