name: CI
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install ragel
        run: sudo apt install ragel
      - name: Build simulator
        run: |
          cd simulator
          make clean && make
      - name: Run tests
        run: |
          cd tests
          make clean && make test-travis
